export const FETCH_PIZZAS_START = 'FETCH_PIZZAS_START';
export const FETCH_PIZZAS_SUCCESS = 'FETCH_PIZZAS_SUCCESS';
export const FETCH_PIZZAS_FAILUER = 'FETCH_PIZZAS_FAILUER';

export const ADD_PIZZA_TO_BASKET = 'ADD_PIZZA_TO_BASKET';

export const SEARCH_PIZZA = 'SEARCH_PIZZA';

export const REMOVE_PIZZA_FROM_BASKET = 'REMOVE_PIZZA_FROM_BASKET';

export const CLEAR_BASKET = 'CLEAR_BASKET';

export const INCREASE_THE_GOODS_COUNT_BY_ID = 'INCREASE_THE_GOODS_COUNT_BY_ID';
export const DECREASE_THE_GOODS_COUNT_BY_ID  = 'DECREASE_THE_GOODS_COUNT_BY_ID';

export const ADD_NOTIFIER = 'ADD_NOTIFIER';
export const REMOVE_NOTIFIER = 'REMOVE_NOTIFIER';
